---
# docker compose -f backup-compose.yml up -d --build --force-recreate
name: pgbackups

services:
  pgbackups:
    container_name: postgres-backup-local-test
    image: rizl4s/postgres-backup-local:16
    build:
      context: ..
      dockerfile: alpine.Dockerfile
      args:
        BASETAG: 16-alpine
    restart: always
    volumes:
      - ./envs:/app/envs
    networks:
      - net-postgres1
      - net-postgres2

networks:
  net-postgres1:
    external: true
  net-postgres2:
    external: true
