---
name: postgres1

services:
  postgres1:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=database1
      - POSTGRES_USER=username1
      - POSTGRES_PASSWORD=password1
    networks:
      - postgres1

networks:
  postgres1:
    name: net-postgres1
    driver: bridge
    external: false
